# Generated by Django 5.0.3 on 2024-03-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_sujet', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('fichier', models.FileField(upload_to='sujets/')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfaxes.cours')),
            ],
        ),
    ]
