# Generated by Django 5.0.3 on 2024-03-22 03:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfaxes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cours',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='type_sujet',
            field=models.CharField(choices=[('TPE', 'Travaux Pratiques Encadrés'), ('CC', 'Contrôle Continu'), ('EXAM', 'Examen')], max_length=4),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=75)),
                ('telephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Entrez un numéro de téléphone valide.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('annee', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfaxes.filiere')),
            ],
            options={
                'verbose_name_plural': 'niveaux',
                'unique_together': {('filiere', 'nom', 'annee')},
            },
        ),
    ]
