# Generated by Django 5.0.3 on 2024-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfaxes', '0003_alter_etudiant_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='type_sujet',
            field=models.CharField(choices=[('TD', 'Travaux Dirigés'), ('TPE', 'Travaux Pratiques Encadrés'), ('CC', 'Contrôle Continu'), ('EXAM', 'Examen')], max_length=4),
        ),
    ]
