# Generated by Django 5.0.3 on 2024-03-23 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfaxes', '0005_cours_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myfaxes.niveau'),
        ),
    ]
