# Generated by Django 5.0.3 on 2024-03-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfaxes', '0007_alter_cours_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='niveau',
        ),
    ]
