# Generated by Django 5.0.3 on 2024-03-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfaxes', '0009_cours_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfaxes.niveau'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(choices=[('1', 'Nineau 1'), ('2', 'Niveau 2'), ('3', 'Niveau 3')], max_length=1),
        ),
    ]
