# Generated by Django 5.0.3 on 2024-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfaxes', '0010_alter_cours_niveau_alter_niveau_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(choices=[('Nineau 1', 'Nineau 1'), ('Nineau 2', 'Niveau 2'), ('Nineau 3', 'Niveau 3')], max_length=10),
        ),
    ]
